In [2]:
%load_ext autoreload
%autoreload 2
import sys 
import os
sys.path.append(os.path.relpath("../test"))
from utilities import *

from algorithms import *

In [4]:
x = np.array([[1, 2, 3], [2, 3, 4], [0, 1, 2], [7, 8, 9]])
x

array([[1, 2, 3],
       [2, 3, 4],
       [0, 1, 2],
       [7, 8, 9]])

In [5]:
 
type(np.array([2])[0].astype(int)) == int
type(int(np.array([2.])[0]))

int

In [6]:
type(np.array([2])[0]) == int

False

In [7]:
tx = build_poly(x, [2, 1, 2])
tx

array([[  1.,   1.,   1.,   2.,   3.,   9.],
       [  1.,   2.,   4.,   3.,   4.,  16.],
       [  1.,   0.,   0.,   1.,   2.,   4.],
       [  1.,   7.,  49.,   8.,   9.,  81.]])

In [8]:
deg = np.array([[1, 2], [3, 4]])
deg[1][1]


4

In [27]:
dim_test = x.shape[1]
deg_min_max_test = [[1,3], [1,3], [1,3]]
A = np.zeros((3**3,3))

In [28]:
A

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [31]:
fill_deg(A, 0, 3**3-1, 0, deg_min_max_test)
A

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  2.],
       [ 1.,  1.,  3.],
       [ 1.,  2.,  1.],
       [ 1.,  2.,  2.],
       [ 1.,  2.,  3.],
       [ 1.,  3.,  1.],
       [ 1.,  3.,  2.],
       [ 1.,  3.,  3.],
       [ 2.,  1.,  1.],
       [ 2.,  1.,  2.],
       [ 2.,  1.,  3.],
       [ 2.,  2.,  1.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  3.],
       [ 2.,  3.,  1.],
       [ 2.,  3.,  2.],
       [ 2.,  3.,  3.],
       [ 3.,  1.,  1.],
       [ 3.,  1.,  2.],
       [ 3.,  1.,  3.],
       [ 3.,  2.,  1.],
       [ 3.,  2.,  2.],
       [ 3.,  2.,  3.],
       [ 3.,  3.,  1.],
       [ 3.,  3.,  2.],
       [ 3.,  3.,  3.]])

In [14]:
a = [1, 2, 3]
b= [4, 5, 6]

In [15]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
x



array([[1, 2, 3],
       [2, 3, 4],
       [0, 1, 2],
       [7, 8, 9]])

In [17]:
build_poly(x, [1, 2, 1])

array([[  1.,   1.,   2.,   4.,   3.],
       [  1.,   2.,   3.,   9.,   4.],
       [  1.,   0.,   1.,   1.,   2.],
       [  1.,   7.,   8.,  64.,   9.]])

In [18]:
x

array([[1, 2, 3],
       [2, 3, 4],
       [0, 1, 2],
       [7, 8, 9]])

In [19]:
fill_deg(A,0,7,0,[[0,1],[0,1],[0,1]])
A[0]

array([ 0.,  0.,  0.])

In [16]:
%load_ext autoreload
%autoreload 2
import sys 
import os
sys.path.append(os.path.relpath("../test"))
from utilities import *

from algorithms import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [17]:
# load data.
height, weight, gender = load_data_from_ex02()

# build sampled x and y.
seed = 1
y = np.expand_dims(gender, axis=1)
X = np.c_[height.reshape(-1), weight.reshape(-1)]
y, X = sample_data(y, X, seed, size_samples=10000)
x, mean_x, std_x = standardize(X)

In [21]:
degree_min = [1] * 30
degree_max = [3] * 30

In [66]:
M = [[1]*30]*27
M = np.zeros((27,30))+1

In [69]:

M = [[1]*30]*27
M = np.zeros((27,30))+1

for k in range(3):
    for j in range(3):
        for i in range(3):
            print(i + 3*j + 9*k)
            M[i + 3*j + 9*k][0] = (i+1)
            M[i + 3*j + 9*k][1] = (j+1)
            M[i + 3*j + 9*k][2] = (k+1)
print(M.astype(int).tolist())

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [2, 1, 2

In [42]:
print([[0]*30]*27)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [3]:
import numpy as np

In [9]:
y = np.zeros((3,1))
y[0,0]=2

In [10]:
y

array([[ 2.],
       [ 0.],
       [ 0.]])